# Generated by Django 5.2.8 on 2025-11-15 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_todo_due_date_alter_note_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='done',
            new_name='completed',
        ),
    ]
