# Generated by Django 5.2.8 on 2025-11-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_completed_todo_done_alter_note_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='activity',
            field=models.CharField(choices=[('shopping', 'Shopping'), ('meeting', 'Meeting'), ('outdoor', 'Outdoor'), ('workout', 'Workout'), ('custom', 'Other (custom)')], default='custom', max_length=50),
        ),
        migrations.AddField(
            model_name='todo',
            name='activity_custom',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
