# Generated by Django 5.2.8 on 2025-11-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_todo_activity_todo_activity_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='reminder',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
