# Generated by Django 5.2.8 on 2025-11-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_todo_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
    ]
