# Generated by Django 5.2.8 on 2026-01-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_note_user_todo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('PENDING', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Done')], default='PENDING', max_length=20),
        ),
    ]
